--------------------------------------------------------------------------------------------------------------

CREATE TABLE security (
    id           NUMBER
        GENERATED BY DEFAULT AS IDENTITY
    PRIMARY KEY,
    private_code NUMBER(6) NOT NULL UNIQUE,
    finger_code  RAW(16) DEFAULT sys_guid()
)

INSERT INTO security ( private_code ) VALUES ( 385318 );

INSERT INTO security ( private_code ) VALUES ( 571112 );

INSERT INTO security ( private_code ) VALUES ( 216993 );

INSERT INTO security ( private_code ) VALUES ( 158355 );

INSERT INTO security ( private_code ) VALUES ( 249877 );

INSERT INTO security ( private_code ) VALUES ( 752701 );

INSERT INTO security ( private_code ) VALUES ( 505647 );

INSERT INTO security ( private_code ) VALUES ( 498127 );

INSERT INTO security ( private_code ) VALUES ( 972843 );

INSERT INTO security ( private_code ) VALUES ( 727218 );

INSERT INTO security ( private_code ) VALUES ( 511825 );

INSERT INTO security ( private_code ) VALUES ( 357219 );

INSERT INTO security ( private_code ) VALUES ( 514211 );

INSERT INTO security ( private_code ) VALUES ( 909719 );

INSERT INTO security ( private_code ) VALUES ( 405679 );

INSERT INTO security ( private_code ) VALUES ( 234019 );

INSERT INTO security ( private_code ) VALUES ( 743741 );

INSERT INTO security ( private_code ) VALUES ( 116522 );

INSERT INTO security ( private_code ) VALUES ( 533272 );

INSERT INTO security ( private_code ) VALUES ( 475124 );

INSERT INTO security ( private_code ) VALUES ( 428897 );

INSERT INTO security ( private_code ) VALUES ( 975446 );

INSERT INTO security ( private_code ) VALUES ( 691923 );

INSERT INTO security ( private_code ) VALUES ( 878070 );

INSERT INTO security ( private_code ) VALUES ( 583879 );

INSERT INTO security ( private_code ) VALUES ( 145510 );

INSERT INTO security ( private_code ) VALUES ( 740221 );

INSERT INTO security ( private_code ) VALUES ( 971947 );

INSERT INTO security ( private_code ) VALUES ( 222534 );

INSERT INTO security ( private_code ) VALUES ( 455850 );

INSERT INTO security ( private_code ) VALUES ( 109985 );

INSERT INTO security ( private_code ) VALUES ( 784392 );

INSERT INTO security ( private_code ) VALUES ( 549155 );

INSERT INTO security ( private_code ) VALUES ( 549155 );

INSERT INTO security ( private_code ) VALUES ( 574412 );

INSERT INTO security ( private_code ) VALUES ( 368751 );

INSERT INTO security ( private_code ) VALUES ( 499632 );

INSERT INTO security ( private_code ) VALUES ( 499632 );

INSERT INTO security ( private_code ) VALUES ( 129433 );

INSERT INTO security ( private_code ) VALUES ( 560082 );

INSERT INTO security ( private_code ) VALUES ( 471300 );

INSERT INTO security ( private_code ) VALUES ( 907174 );

INSERT INTO security ( private_code ) VALUES ( 474778 );

INSERT INTO security ( private_code ) VALUES ( 569662 );

--------------------------------------------------------------------------------------------------------------

    

CREATE TABLE profession (
   id NUMBER
        GENERATED BY DEFAULT AS IDENTITY
    PRIMARY KEY,
    name VARCHAR2(30) NOT NULL UNIQUE
);

INSERT INTO profession ( name ) VALUES ( 'Çörekçi' );

INSERT INTO profession ( name ) VALUES ( 'Mal qebulu/Anbardar ' );

INSERT INTO profession ( name ) VALUES ( 'Qablasdirici ' );

INSERT INTO profession ( name ) VALUES ( 'Satici-kassir ' );

INSERT INTO profession ( name ) VALUES ( 'Satis üzre kömekçi ' );

INSERT INTO profession ( name ) VALUES ( 'Xezinadar ' );

INSERT INTO profession ( name ) VALUES ( 'Anbar üzre kömekçi (Fehle) ' );

INSERT INTO profession ( name ) VALUES ( 'Qessab ' );

INSERT INTO profession ( name ) VALUES ( 'Mallarin qebuledicisi ' );

INSERT INTO profession ( name ) VALUES ( 'Temizlik iscisi ' );

--------------------------------------------------------------------------------------------------------------


CREATE TABLE worker_secret_info
(
    id                 NUMBER
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,
    worker_id          NUMBER       NOT NULL UNIQUE,
    home_phone         NUMBER(7),
    home_address       VARCHAR2(50) NOT NULL,
    email              VARCHAR2(50) NOT NULL UNIQUE,
    marital_status     VARCHAR2(5)  NOT NULL,
    number_of_children NUMBER(1)    NOT NULL,
    education          VARCHAR(7)   NOT NULL,
    sallary_card_code  VARCHAR2(15) NOT NULL UNIQUE,
    passaport_code     NUMBER(7)    NOT NULL UNIQUE,
    fin_code           VARCHAR2(6)  NOT NULL,
    finger_code_id     NUMBER       NOT NULL UNIQUE
);

insert INTO worker_secret_info (worker_id, home_phone, home_address, email, marital_status, number_of_children, education,sallary_card_code, passaport_code, fin_code, finger_code_id) values (1,5673410, 'Nizami Kuc., 66', 'akif_agalorov@fake.com', 'Evli', 1, 'Ali', 10010203040574,7056130, '1F5W0D', 1);
insert INTO worker_secret_info (worker_id, home_phone, home_address, email, marital_status, number_of_children, education,sallary_card_code, passaport_code, fin_code, finger_code_id) values (2,6279833, 'N. Yusifbeyli Kuc. 75', 'asiman_ceferov@fake.com', 'Subay', 0, 'Orta', 564707789158585,7653448, 'TB6OQ7', 2);
insert INTO worker_secret_info (worker_id, home_phone, home_address, email, marital_status, number_of_children, education,sallary_card_code, passaport_code, fin_code, finger_code_id) values (3,9734818, '28 May Kuc. 20/Fuzuli Kuc. 65 ', 'bahadir_ferecov@fake.com', 'Evli', 1, 'Ali', 775672561367067,7551353, '7NJGYR', 3);
insert INTO worker_secret_info (worker_id, home_phone, home_address, email, marital_status, number_of_children, education,sallary_card_code, passaport_code, fin_code, finger_code_id) values (4,8133834, 'R. Rza Kuc. 15', 'celal_novruzov@fake.com', 'Evli', 2, 'Ali', 582394457309784,6981257, 'ECWEJW', 4);
insert INTO worker_secret_info (worker_id, home_phone, home_address, email, marital_status, number_of_children, education,sallary_card_code, passaport_code, fin_code, finger_code_id) values (5,8950063, 'Zix Sossesi Kuc. 4', 'elariz_resulov@fake.com', 'Subay', 0, 'Orta', 778007755974771,4651875, '30E94I', 5);
insert INTO worker_secret_info (worker_id, home_phone, home_address, email, marital_status, number_of_children, education,sallary_card_code, passaport_code, fin_code, finger_code_id) values (6,1354175, 'A. Celilov Kuc. 3', 'elturan_seyidov@fake.com', 'Evli', 1, 'Orta', 784471404472587,4419792, 'EFGDEA', 6);
insert INTO worker_secret_info (worker_id, home_phone, home_address, email, marital_status, number_of_children, education,sallary_card_code, passaport_code, fin_code, finger_code_id) values (7,8334214, 'SAMED VURGUN Kuc, 56', 'zaur_memmedyarov@fake.com', 'Evli', 2, 'Natamam', 667362290698993,7416698, 'VZU2YF', 7);
insert INTO worker_secret_info (worker_id, home_phone, home_address, email, marital_status, number_of_children, education,sallary_card_code, passaport_code, fin_code, finger_code_id) values (8,7027352, 'AGA NEMATULLA Kuc, 10', 'elsad_bayramov@fake.com', 'Subay', 0, 'Ali', 422368703392470,5072166, '8KBRGK', 8);
insert INTO worker_secret_info (worker_id, home_phone, home_address, email, marital_status, number_of_children, education,sallary_card_code, passaport_code, fin_code, finger_code_id) values (9,2011383, 'S. Vurgun Kuc. 26', 'ferda_bunyadov@fake.com', 'Evli', 4, 'Ali', 175370947590822,1844727, 'ZO98OG', 9);
insert INTO worker_secret_info (worker_id, home_phone, home_address, email, marital_status, number_of_children, education,sallary_card_code, passaport_code, fin_code, finger_code_id) values (10,2245526, 'H. Zardabi Kuc. 84', 'ferahim_cebiyev@fake.com', 'Evli', 3, 'Ali', 390908031227043,6422187, 'DPL0UF', 10);
insert INTO worker_secret_info (worker_id, home_phone, home_address, email, marital_status, number_of_children, education,sallary_card_code, passaport_code, fin_code, finger_code_id) values (11,9216770, 'E. Veliyev Kuc. 16', 'gulbala_haciyev@fake.com', 'Subay', 0, 'Orta', 110541865039461,1233614, 'UJ6MSQ', 11);
insert INTO worker_secret_info (worker_id, home_phone, home_address, email, marital_status, number_of_children, education,sallary_card_code, passaport_code, fin_code, finger_code_id) values (12,4289742, 'A. Meherremov Kuc. 34', 'imran_hesenov@fake.com', 'Evli', 1, 'Ali', 930404623652233,7766716, '758QE7', 12);
insert INTO worker_secret_info (worker_id, home_phone, home_address, email, marital_status, number_of_children, education,sallary_card_code, passaport_code, fin_code, finger_code_id) values (13,2193241, 'Istiqlaliyyet Kuc. 31 ', 'ismet_kazimov@fake.com', 'Evli', 2, 'Orta', 464873849258420,4687900, '2GP4LQ', 13);
insert INTO worker_secret_info (worker_id, home_phone, home_address, email, marital_status, number_of_children, education,sallary_card_code, passaport_code, fin_code, finger_code_id) values (14,5322007, 'S. Rehimov Kuc. 126/64', 'niyaz_qarayev@fake.com', 'Subay', 0, 'Ali', 545973700087196,3218916, 'IW0IWL', 14);
insert INTO worker_secret_info (worker_id, home_phone, home_address, email, marital_status, number_of_children, education,sallary_card_code, passaport_code, fin_code, finger_code_id) values (15,3811724, 'Naxcivani Kuc. 6','rovsen_qurbanov@fake.com', 'Subay', 0, 'Ali', 322939628059968,4295773, 'BI4UMP', 15);
insert INTO worker_secret_info (worker_id, home_phone, home_address, email, marital_status, number_of_children, education,sallary_card_code, passaport_code, fin_code, finger_code_id) values (16,5927411, 'Heyder Eliyev Prosp. 2 A', 'umud_orucov@fake.com', 'Evli', 3, 'Orta', 471674225147783,1997135, 'OQZLVP', 16);
insert INTO worker_secret_info (worker_id, home_phone, home_address, email, marital_status, number_of_children, education,sallary_card_code, passaport_code, fin_code, finger_code_id) values (17,6970342, 'C. Cabbarli Kuc. 27', 'telman_seyidov@fake.com', 'Evli', 1, 'Ali', 553840381547883,5642829, 'C9N54M', 17);
insert INTO worker_secret_info (worker_id, home_phone, home_address, email, marital_status, number_of_children, education,sallary_card_code, passaport_code, fin_code, finger_code_id) values (18,6532868, 'S. Vurgun Kuc., 77', 'xelil_huseynov@fake.com', 'Evli', 2, 'Ali', 898262020180556,7183287, '8MLTVD', 18);
insert INTO worker_secret_info (worker_id, home_phone, home_address, email, marital_status, number_of_children, education,sallary_card_code, passaport_code, fin_code, finger_code_id) values (19,4052274, 'Y. Seferov Kuc. 20', 'yadigar_recebov@fake.com', 'Subay', 0, 'Orta', 635262696428674,4022602, '97GARY', 19);
insert INTO worker_secret_info (worker_id, home_phone, home_address, email, marital_status, number_of_children, education,sallary_card_code, passaport_code, fin_code, finger_code_id) values (20,7773226, 'Xetai Prosp. 5', 'zeynal_esedli@fake.com', 'Evli', 4, 'Ali', 882090802110166,3852877, 'AF54CO', 20);
insert INTO worker_secret_info (worker_id, home_phone, home_address, email, marital_status, number_of_children, education,sallary_card_code, passaport_code, fin_code, finger_code_id) values (21,4672627, 'M. Huseyn Kuc. 77', 'sukur_eliyev@fake.com', 'Subay', 0, 'Ali', 570114207925673,8974350, 'DR7XVP', 21);
insert INTO worker_secret_info (worker_id, home_phone, home_address, email, marital_status, number_of_children, education,sallary_card_code, passaport_code, fin_code, finger_code_id) values (22,6383980, 'M. Huseyn Kuc. 77', 'aygul_aslanova@fake.com', 'Evli', 1, 'Ali', 297197039275612,8221130, 'B0U6E0', 22);
insert INTO worker_secret_info (worker_id, home_phone, home_address, email, marital_status, number_of_children, education,sallary_card_code, passaport_code, fin_code, finger_code_id) values (23,5378922, 'Neftciler Prosp. 61', 'brilyant_bagirzade@fake.com', 'Evli', 3, 'Orta', 682554518712284,5964224, 'HOVDX9', 23);
insert INTO worker_secret_info (worker_id, home_phone, home_address, email, marital_status, number_of_children, education,sallary_card_code, passaport_code, fin_code, finger_code_id) values (24,7330803, 'Y. Memmedeliyev Kuc. 6', 'cahan_babayeva@fake.com', 'Subay', 0, 'Ali', 751451190365385,6766015, 'JYHKS1', 24);
insert INTO worker_secret_info (worker_id, home_phone, home_address, email, marital_status, number_of_children, education,sallary_card_code, passaport_code, fin_code, finger_code_id) values (25,2742717, 'Mir-Celal Kuc. 15', 'cinare_ceferova@fake.com', 'Evli', 2, 'Ali', 173969722593161,2589149, 'TI3SD8', 25);
insert INTO worker_secret_info (worker_id, home_phone, home_address, email, marital_status, number_of_children, education,sallary_card_code, passaport_code, fin_code, finger_code_id) values (26,1873282, 'O. Kerimov Kuc. 54', 'dunya_ehmedova@fake.com', 'Subay', 0, 'Orta', 375655192067083,4922681, 'H14HYK', 26);
insert INTO worker_secret_info (worker_id, home_phone, home_address, email, marital_status, number_of_children, education,sallary_card_code, passaport_code, fin_code, finger_code_id) values (27,5031779, 'Bayil Qes., Q. Abbasov Kuc. 72/1a', 'elaner_hesenova@fake.com', 'Evli', 3, 'Ali', 914870889383290,5178545, 'U3PVLQ', 27);
insert INTO worker_secret_info (worker_id, home_phone, home_address, email, marital_status, number_of_children, education,sallary_card_code, passaport_code, fin_code, finger_code_id) values (28,3361387, 'Nizami Kuc.53a ', 'emine_ibrahimova@fake.com', 'Subay', 0, 'Ali', 507981698286514,9116767, '8VHO5E', 28);
insert INTO worker_secret_info (worker_id, home_phone, home_address, email, marital_status, number_of_children, education,sallary_card_code, passaport_code, fin_code, finger_code_id) values (29,9179535, 'Y. Seferov Kuc. 10/13 ', 'fatihe_ismayilzade@fake.com', 'Evli', 1, 'Ali', 444685425903553,8295247, '5B2ACP', 29);
insert INTO worker_secret_info (worker_id, home_phone, home_address, email, marital_status, number_of_children, education,sallary_card_code, passaport_code, fin_code, finger_code_id) values (30,5315595, 'M. Huseyn Kuc. 59 ', 'gulnaer_kazimova@fake.com', 'Subay', 0, 'Natamam', 759412030305313,2312943, '6HUJJV', 30);
insert INTO worker_secret_info (worker_id, home_phone, home_address, email, marital_status, number_of_children, education,sallary_card_code, passaport_code, fin_code, finger_code_id) values (31,6170923, 'H. Abdullayev Kuc. 11 ', 'hicrazn_ismayilzade@fake.com', 'Evli', 3, 'Ali', 837440733179172,2312943, '1QEWXZ', 31);
insert INTO worker_secret_info (worker_id, home_phone, home_address, email, marital_status, number_of_children, education,sallary_card_code, passaport_code, fin_code, finger_code_id) values (32,6477164, 'Naximov Kuc. 10, 66 Az1000, Absheron', 'ilahe_quluzade@fake.com', 'Subay', 0, 'Orta', 607961046360377,8177009, '1QEWXZ', 32);
insert INTO worker_secret_info (worker_id, home_phone, home_address, email, marital_status, number_of_children, education,sallary_card_code, passaport_code, fin_code, finger_code_id) values (33,8615256, 'Tagizade Kucesi. 11, 66 Az1000, Absheron', 'kamile_melikzade@fake.com', 'Evli', 1, 'Ali', 994549464020411,4556887, 'S9DHNI', 33);
insert INTO worker_secret_info (worker_id, home_phone, home_address, email, marital_status, number_of_children, education,sallary_card_code, passaport_code, fin_code, finger_code_id) values (34,3742615, 'Serifzade Kuc. 116 , Absheron', 'lale_mirzezade@fake.com', 'Evli', 1, 'Ali', 246846525721030,4065111, 'HRMPJB', 34);
insert INTO worker_secret_info (worker_id, home_phone, home_address, email, marital_status, number_of_children, education,sallary_card_code, passaport_code, fin_code, finger_code_id) values (35,9220341, 'Senaye Kuc 6, 66 Az1000, Absheron', 'nahide_resulova@fake.com', 'Subay', 0, 'Natamam', 286741928114872,7492927, 'FBLGH8', 35);
insert INTO worker_secret_info (worker_id, home_phone, home_address, email, marital_status, number_of_children, education,sallary_card_code, passaport_code, fin_code, finger_code_id) values (36,7359744, 'Ataturk Kuc. 16', '', 'Evli', 5, 'Orta', 946436881275237,1250900, '086QL4', 36);
insert INTO worker_secret_info (worker_id, home_phone, home_address, email, marital_status, number_of_children, education,sallary_card_code, passaport_code, fin_code, finger_code_id) values (37,9181423, 'Fuzuli Kuc. 66', 'qaratel_imanova@fake.com', 'Evli', 1, 'Ali', 486923300798660,3957203, 'CIBG4Q', 37);
insert INTO worker_secret_info (worker_id, home_phone, home_address, email, marital_status, number_of_children, education,sallary_card_code, passaport_code, fin_code, finger_code_id) values (38,7919366, 'HEYDAR ALIYEV Kuc. 15', 'reqsane_ferecova@fake.com', 'Evli', 1, 'Ali', 568284797677926,7513637, 'J8BQFO', 38);
insert INTO worker_secret_info (worker_id, home_phone, home_address, email, marital_status, number_of_children, education,sallary_card_code, passaport_code, fin_code, finger_code_id) values (39,2504322, 'Zerife Eliyeva Kuc. 50', 'simuzer_cabbarova@fake.com', 'Subay', 0, 'Natamam', 803377577741506,8803266, '5U30DU', 39);
insert INTO worker_secret_info (worker_id, home_phone, home_address, email, marital_status, number_of_children, education,sallary_card_code, passaport_code, fin_code, finger_code_id) values (40,2017715, 'S. Orucov Kuc. 10, Absheron', 'semsiyye_qarayeva@fake.com', 'Evli', 2, 'Ali', 124203966723800,5070506, '0Q7ZSJ', 40);
insert INTO worker_secret_info (worker_id, home_phone, home_address, email, marital_status, number_of_children, education,sallary_card_code, passaport_code, fin_code, finger_code_id) values (41,7763911, 'Samil Kamilov Kuc. 7 ', 'turan_imanova@fake.com', 'Subay', 0, 'Ali', 487671841829514,7553992, 'LWNUPT', 41);
insert INTO worker_secret_info (worker_id, home_phone, home_address, email, marital_status, number_of_children, education,sallary_card_code, passaport_code, fin_code, finger_code_id) values (42,4385400, 'Sulh Prosp. 3 ', 'akif_agalorov@fake.com', 'Evli', 1, 'Ali', 416957958797413,5000497, 'G2BEKA', 42);



--------------------------------------------------------------------------------------------------------------
CREATE TABLE worker (
    id      NUMBER
        GENERATED BY DEFAULT AS IDENTITY
    PRIMARY KEY,
    name    VARCHAR2(15) NOT NULL,
    surname VARCHAR(15) NOT NULL, 
    gender  CHAR(1),
    age     DATE,
    phone   VARCHAR2(10)
)

insert into  worker (name,surname,gender,age,phone) values('Akif','Agalarov','K','11/03/2001','6322221000')
insert into  worker (name,surname,gender,age,phone) values('Asiman','Ceferov','K','23/10/1973','6062476553',)
insert into  worker (name,surname,gender,age,phone) values('Bahadur','Ferecov','K','04/03/1991','7257932322')
insert into  worker (name,surname,gender,age,phone) values('Celal','Novruzov','K','11/07/1996','3769580365')
insert into  worker (name,surname,gender,age,phone) values('Elariz','Resulov','K','21/05/2001','5163378734')
insert into  worker (name,surname,gender,age,phone) values('Elturan','Seyidov','K','09/09/1978','8862272066')
insert into  worker (name,surname,gender,age,phone) values('Zaur','Memmedyarov','K','29/02/2000','4661287831')
insert into  worker (name,surname,gender,age,phone) values('Elaad','Bayramov','K','24/01/1984','9067459278')
insert into  worker (name,surname,gender,age,phone) values('Ferda','Bünyadov','K','06/06/1993','8458206404')
insert into  worker (name,surname,gender,age,phone) values('Ferahim','Cebiyev','K','17/04/1999','2069359053')
insert into  worker (name,surname,gender,age,phone) values('Fikret','Efendiyev','K','19/12/1975','8206591871')
insert into  worker (name,surname,gender,age,phone) values('Gülbala','Haciyev','K','12/08/1974','2520247665')
insert into  worker (name,surname,gender,age,phone) values('Imran','Hesenov','K','18/01/1973','8539380975')
insert into  worker (name,surname,gender,age,phone) values('Ismet','Kazimov','K','25/05/1972','9120327059')
insert into  worker (name,surname,gender,age,phone) values('Niyaz','Qarayev','K','31/12/1973','3073701802')
insert into  worker (name,surname,gender,age,phone) values('Rövsen','Qurbanlov','K','07/10/1986','2379814124')
insert into  worker (name,surname,gender,age,phone) values('Ümid','Orucov','K','01/04/1976','8301588853')
insert into  worker (name,surname,gender,age,phone) values('Telman','Seyidov','K','28/09/1981','1935151320')
insert into  worker (name,surname,gender,age,phone) values('Xelil','Hüseynov','K','22/08/1989','7437883815')
insert into  worker (name,surname,gender,age,phone) values('Yadigar','Recebov','K','24/04/1974','9078431376')
insert into  worker (name,surname,gender,age,phone) values('Zeynal','Esedli','K','23/12/1990','6093952027')
insert into  worker (name,surname,gender,age,phone) values('Sükür','Eliyev','Q','03/02/2002','3043475789')
insert into  worker (name,surname,gender,age,phone) values('Aygül','Aslanova','Q','16/03/1976','1489483115')
insert into  worker (name,surname,gender,age,phone) values('Brilyant','Bagirrzade','Q','03/09/1997','5895796918')
insert into  worker (name,surname,gender,age,phone) values('Cahan',' Babayeva','Q','28/04/1997','6513371302')
insert into  worker (name,surname,gender,age,phone) values('Çinare','Ceferova','Q','13/12/1987','9773126661')
insert into  worker (name,surname,gender,age,phone) values('Dünya','Ehmedova','Q','29/06/1998','5275396531')
insert into  worker (name,surname,gender,age,phone) values('Elnare','Hesenova','Q','07/10/1983','8712486588')
insert into  worker (name,surname,gender,age,phone) values('Emine','Ibrahimova','Q','27/08/1998','7153027592')
insert into  worker (name,surname,gender,age,phone) values('Fatihe','Ismayilova','Q','30/06/1995','7046982084')
insert into  worker (name,surname,gender,age,phone) values('Gülare','Kazimova','Q','02/12/1974','6487304445')
insert into  worker (name,surname,gender,age,phone) values('Hicran','Ismayilzade','Q','15/12/1980','7967552784')
insert into  worker (name,surname,gender,age,phone) values('Ilahe','Quluzade','Q','21/02/1986','7967552784')
insert into  worker (name,surname,gender,age,phone) values('Kamile','Melikzade','Q','01/05/1987','6520187885')
insert into  worker (name,surname,gender,age,phone) values('Lale','Mirzezade','Q','21/12/1986','4401705905')
insert into  worker (name,surname,gender,age,phone) values('Nahide','Resulova','Q','26/04/1982','5252015098')
insert into  worker (name,surname,gender,age,phone) values('Ofeliya','Novruzlu','Q','21/06/1981','1334132582')
insert into  worker (name,surname,gender,age,phone) values('Qaratel','Imanova','Q','14/11/1972','6662601835')
insert into  worker (name,surname,gender,age,phone) values('Reqsane','Ferecova','Q','17/01/1981','5010994584')
insert into  worker (name,surname,gender,age,phone) values('Simuzer','Cabbarova','Q','23/02/1980','6007235923')
insert into  worker (name,surname,gender,age,phone) values('Semsiyye','Qarayeva','Q','10/12/1980','1899066426')
insert into  worker (name,surname,gender,age,phone) values('Turan','Imanova','Q','10/12/1980','5832781864')

--------------------------------------------------------------------------------------------------------------





